### ISSUE TITLE
about rsync

### ISSUE THREAD

**Issue by XuBlack** [amorehead/DIPS-Plus#1]
When I use the commend
 `rsync -rlpt -v -z --delete --port=33444 --include='*.gz' --include='*.xz' --include='*/' --exclude '*' rsync.rcsb.org::ftp_data/biounit/coordinates/divided/ project/datasets/DIPS/raw/pdb`, 
it appears the error 
`@ERROR: max connections (25) reached -- try again later
rsync error: error starting client-server protocol (code 5) at main.c(1666) [Receiver=3.1.2]`

Do you know how to solve this problem?
Thanks!

**Comment by amorehead** [comment]
Hi, @XuBlack. To see if the RCSB's server is down, I tried running the following command on my local machine. I am currently able to download PDB complexes using this URL as shown below. To help you troubleshoot, are you using any kind of virtual private network (VPN) while you are trying to run the rsync command?

rsync command:

rsync -rlpt -v -z --delete --port=33444 --include='*.gz' --include='*.xz' --include='*/' --exclude '*' \
rsync.rcsb.org::ftp_data/biounit/coordinates/divided/ project/datasets/DIPS/raw/pdb

Command output: ![image](https://user-images.githubusercontent.com/7051982/126362988-9f2fa781-9687-4e92-9087-1697c12bed24.png)

**Comment by XuBlack** [comment]
Thanks for your reply. 

I have succeed in running the command after restarting the rsync service.
