### ISSUE TITLE
regarding random split

### ISSUE THREAD

**Issue by octavian-ganea** [amorehead/DIPS-Plus#2]
hi,

Thanks for putting this dataset out. Looking at https://github.com/amorehead/DIPS-Plus/blob/main/project/datasets/builder/partition_dataset_filenames.py#L68 it seems to me that the train/val/test splits are done randomly as opposed to a "per folder" option. For example, pairs 3a74.pdb1_0.dill and 3a74.pdb2_0.dill could end up in different splits, but I assume they are very similar (which, at a glance, seems to be the case in terms of the sequences of residue names, but not in terms of 3d coordinates). 

Can this be an issue for ml pipelines?

thanks

**Comment by amorehead** [comment]
Hi, @octavian-ganea.

Thank you for pointing this out. I neglected to update this file after making a similar change in another (currently private) repository. I have just pushed a [change](https://github.com/amorehead/DIPS-Plus/commit/8820aedd38905c44acc5ee212824e1835c6f4993) making the "per folder" dataset filename splits now being the default.

If you have any other questions or concerns, please let me know. Thanks again!
